### ISSUE TITLE
[인프라] redis

### ISSUE THREAD

**Issue by tlsdhsdb** [SSAFY-DANGO/BackEnd#14]
In GitLab by @wjsrudgid on Mar 12, 2024, 09:19

- [DockerHub-Redis](https://hub.docker.com/_/redis)
- [docker-compose로 Redis 컨테이너 실행하기](https://bskyvision.com/entry/docker-docker-compose%EB%A1%9C-Redis-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0)

```  
version: "3.8"

services:  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf
```
